# Generated by Django 5.0.9 on 2025-10-07 11:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RPTKA', 'RPTKA'), ('IMTA', 'IMTA/Notifikasi'), ('VISA', 'Visa'), ('KITAS', 'KITAS'), ('SKTT', 'SKTT'), ('PASSPORT', 'Paspor')], max_length=20)),
                ('document_number', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('EXPIRED', 'Kedaluwarsa')], default='ACTIVE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RenewalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(default=django.utils.timezone.localdate)),
                ('process_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Disetujui'), ('COMPLETED', 'Selesai')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('new_document_number', models.CharField(blank=True, max_length=100)),
                ('new_issue_date', models.DateField(blank=True, null=True)),
                ('new_expiry_date', models.DateField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_history', to='dashboard.document')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('passport_number', models.CharField(max_length=50, unique=True)),
                ('nationality', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('position', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='workers/photos/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='dashboard.company')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dashboard.worker'),
        ),
    ]
