# Generated by Django 5.0.9 on 2025-10-07 12:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Perusahaan', 'verbose_name_plural': 'Perusahaan'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Dokumen', 'verbose_name_plural': 'Dokumen'},
        ),
        migrations.AlterModelOptions(
            name='renewalhistory',
            options={'verbose_name': 'Riwayat Perpanjangan', 'verbose_name_plural': 'Riwayat Perpanjangan'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Pekerja', 'verbose_name_plural': 'Pekerja'},
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kontak person'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=255, verbose_name='Industri'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_number',
            field=models.CharField(max_length=100, verbose_name='Nomor dokumen'),
        ),
        migrations.AlterField(
            model_name='document',
            name='expiry_date',
            field=models.DateField(verbose_name='Tanggal berakhir'),
        ),
        migrations.AlterField(
            model_name='document',
            name='issue_date',
            field=models.DateField(verbose_name='Tanggal terbit'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Aktif'), ('EXPIRED', 'Kedaluwarsa')], default='ACTIVE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('RPTKA', 'RPTKA'), ('IMTA', 'IMTA/Notifikasi'), ('VISA', 'Visa'), ('KITAS', 'KITAS'), ('SKTT', 'SKTT'), ('PASSPORT', 'Paspor')], max_length=20, verbose_name='Jenis'),
        ),
        migrations.AlterField(
            model_name='document',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dashboard.worker', verbose_name='Pekerja'),
        ),
        migrations.AlterField(
            model_name='renewalhistory',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_history', to='dashboard.document', verbose_name='Dokumen'),
        ),
        migrations.AlterField(
            model_name='renewalhistory',
            name='new_document_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nomor dokumen baru'),
        ),
        migrations.AlterField(
            model_name='renewalhistory',
            name='new_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal berakhir baru'),
        ),
        migrations.AlterField(
            model_name='renewalhistory',
            name='new_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal terbit baru'),
        ),
        migrations.AlterField(
            model_name='renewalhistory',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Catatan'),
        ),
        migrations.AlterField(
            model_name='renewalhistory',
            name='process_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Disetujui'), ('COMPLETED', 'Selesai')], default='PENDING', max_length=20, verbose_name='Status proses'),
        ),
        migrations.AlterField(
            model_name='renewalhistory',
            name='submission_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Tanggal pengajuan'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='birth_date',
            field=models.DateField(verbose_name='Tanggal lahir'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='dashboard.company', verbose_name='Perusahaan'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='nationality',
            field=models.CharField(max_length=100, verbose_name='Kewarganegaraan'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='passport_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nomor paspor'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='workers/photos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.CharField(max_length=255, verbose_name='Jabatan'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal mulai kerja'),
        ),
    ]
